repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.2"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/commitizen-tools/commitizen
    rev: "v4.13.8"
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.19.1"
    hooks:
    -   id: mypy
        additional_dependencies:
          - click>=8.3.1
          - typer>=0.24.0
          - rich>=14.3.2
          - pytest>=9.0.0
          - pytest-mock>=3.15.0
